name: example
description: An example web server using the PathRouter plugin.

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  pathrouter:
    path: ../
  shelf: ^0.7.2

dev_dependencies:
  pedantic: ^1.0.0
